pulumi config set region "us-east-1"
pulumi config set accountId "108949145303"
pulumi config set privateSubnetTagName "type"
pulumi config set privateSubnetTagValue "PRIVATE"
pulumi config set vpcName "MainVpc"